<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPScSwkW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPScSwkW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPScSwkW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPScSwkW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPScSwkW\App_KernelDevDebugContainer([
    'container.build_hash' => 'PScSwkW',
    'container.build_id' => 'e62c9f53',
    'container.build_time' => 1595955108,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPScSwkW');
